"""v1_initial_schema

Revision ID: 6f3c64bad0b4
Revises: 
Create Date: 2026-07-25 23:11:44.166524

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f3c64bad0b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('monthly_query_limit', sa.Integer(), server_default='10000', nullable=True),
    sa.Column('monthly_index_limit', sa.Integer(), server_default='1000', nullable=True),
    sa.Column('max_products', sa.Integer(), server_default='5000', nullable=True),
    sa.Column('region', sa.String(length=32), server_default='us-east-1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("region <> ''", name='ck_organizations_region'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('analytics_daily',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_queries', sa.Integer(), server_default='0', nullable=True),
    sa.Column('unique_queries', sa.Integer(), server_default='0', nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), server_default='0', nullable=True),
    sa.Column('zero_result_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('cache_hit_rate', sa.Float(), server_default='0', nullable=True),
    sa.Column('top_queries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('top_zero_result_queries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'date')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), server_default='60', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_org', 'api_keys', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_org_actor', 'audit_logs', ['organization_id', 'actor_id'], unique=False)
    op.create_index('idx_audit_org_resource', 'audit_logs', ['organization_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_org_time', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('boost_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('query_pattern', sa.String(length=255), nullable=True),
    sa.Column('attribute_name', sa.String(length=255), nullable=True),
    sa.Column('attribute_value', sa.String(length=255), nullable=True),
    sa.Column('boost_factor', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_boosts_org', 'boost_rules', ['organization_id'], unique=False)
    op.create_table('catalog_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_integrations_org', 'catalog_integrations', ['organization_id'], unique=False)
    op.create_table('merchandising_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('query_exact_match', sa.String(length=255), nullable=False),
    sa.Column('pinned_items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('hidden_items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'query_exact_match', name='uix_org_query')
    )
    op.create_index('idx_merchandising_org_query', 'merchandising_rules', ['organization_id', 'query_exact_match'], unique=False)
    op.create_table('merchant_stores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_merchant_stores_organization', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_merchant_stores_id_organization'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_merchant_stores_org_external_id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_merchant_stores_org_slug')
    )
    op.create_index('idx_merchant_stores_org_status', 'merchant_stores', ['organization_id', 'status'], unique=False)
    op.create_table('pinned_products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('query_pattern', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), server_default='1', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pinned_org_query', 'pinned_products', ['organization_id', 'query_pattern'], unique=False)
    op.create_table('redirect_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('query_pattern', sa.String(length=255), nullable=False),
    sa.Column('redirect_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redirects_org_query', 'redirect_rules', ['organization_id', 'query_pattern'], unique=False)
    op.create_table('sellers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_sellers_organization', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_sellers_id_organization'),
    sa.UniqueConstraint('organization_id', 'external_id', name='uq_sellers_org_external_id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_sellers_org_slug')
    )
    op.create_index('idx_sellers_org_status', 'sellers', ['organization_id', 'status'], unique=False)
    op.create_table('synonyms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('synonyms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_synonyms_org', 'synonyms', ['organization_id'], unique=False)
    op.create_table('tenant_configs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('has_ingested_catalog', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_merchandising_rules', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enable_semantic', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('enable_personalization', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('enable_image_search', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('rrf_keyword_weight', sa.Float(), server_default='0.6', nullable=True),
    sa.Column('rrf_vector_weight', sa.Float(), server_default='0.4', nullable=True),
    sa.Column('typo_tolerance', sa.Integer(), server_default='2', nullable=True),
    sa.Column('searchable_fields', postgresql.ARRAY(sa.String()), server_default='{title,description,brand,category}', nullable=True),
    sa.Column('facet_fields', postgresql.ARRAY(sa.String()), server_default='{brand,category}', nullable=True),
    sa.Column('widget_primary_color', sa.String(length=7), server_default='#6366f1', nullable=True),
    sa.Column('widget_font_family', sa.String(length=100), server_default='Inter', nullable=True),
    sa.Column('widget_position', sa.String(length=20), server_default='center', nullable=True),
    sa.Column('widget_placeholder', sa.Text(), server_default='Search products...', nullable=True),
    sa.Column('out_of_stock_behavior', sa.String(length=20), server_default='demote', nullable=True),
    sa.Column('webhook_urls', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('allowed_domains', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('tenant_users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String()), server_default='{"user"}', nullable=True),
    sa.Column('has_consented_to_personalization', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('behavior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'id')
    )
    op.create_index('idx_tenant_users_org_behavior', 'tenant_users', ['behavior'], unique=False, postgresql_using='gin')
    op.create_index('idx_tenant_users_org_email', 'tenant_users', ['organization_id', 'email'], unique=False)
    op.create_index('idx_tenant_users_org_preferences', 'tenant_users', ['preferences'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tenant_users_seller_id'), 'tenant_users', ['seller_id'], unique=False)
    op.create_table('catalogs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=20), server_default='product', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("resource_type IN ('product', 'document', 'asset', 'content')", name='ck_catalogs_resource_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_catalogs_organization', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id', 'organization_id'], ['sellers.id', 'sellers.organization_id'], name='fk_catalogs_seller_organization'),
    sa.ForeignKeyConstraint(['store_id', 'organization_id'], ['merchant_stores.id', 'merchant_stores.organization_id'], name='fk_catalogs_store_organization'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_catalogs_id_organization'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_catalogs_org_slug')
    )
    op.create_index('idx_catalogs_org_status', 'catalogs', ['organization_id', 'status'], unique=False)
    op.create_table('tenant_activities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['tenant_users.organization_id', 'tenant_users.id'], name='fk_tenant_activities_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_activities_org_type_created', 'tenant_activities', ['organization_id', 'activity_type', 'created_at'], unique=False)
    op.create_index('idx_tenant_activities_org_user_created', 'tenant_activities', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tenant_activities_seller_id'), 'tenant_activities', ['seller_id'], unique=False)
    op.create_table('tenant_conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=32), server_default='rest', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['tenant_users.organization_id', 'tenant_users.id'], name='fk_tenant_conversations_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'id')
    )
    op.create_index('idx_tenant_conversations_org_last_message', 'tenant_conversations', ['organization_id', 'last_message_at'], unique=False)
    op.create_index('idx_tenant_conversations_org_user_created', 'tenant_conversations', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tenant_conversations_seller_id'), 'tenant_conversations', ['seller_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_org_time', 'usage_events', ['organization_id', 'created_at'], unique=False)
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=True),
    sa.Column('parent_item_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_system', sa.String(length=50), server_default='manual', nullable=False),
    sa.Column('source_version', sa.String(length=255), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('index_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('index_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("index_status IN ('pending', 'processing', 'indexed', 'failed', 'dead')", name='ck_catalog_items_index_status'),
    sa.CheckConstraint("resource_type IN ('product', 'document', 'asset', 'content')", name='ck_catalog_items_resource_type'),
    sa.ForeignKeyConstraint(['catalog_id', 'organization_id'], ['catalogs.id', 'catalogs.organization_id'], name='fk_catalog_items_catalog_organization', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id', 'catalog_id', 'organization_id'], ['catalog_items.id', 'catalog_items.catalog_id', 'catalog_items.organization_id'], name='fk_catalog_items_parent_catalog_organization'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'catalog_id', 'organization_id', name='uq_catalog_items_id_catalog_org'),
    sa.UniqueConstraint('organization_id', 'catalog_id', 'external_id', name='uq_catalog_items_org_catalog_external_id')
    )
    op.create_index('idx_catalog_items_document', 'catalog_items', ['document'], unique=False, postgresql_using='gin')
    op.create_index('idx_catalog_items_index_status', 'catalog_items', ['organization_id', 'catalog_id', 'index_status'], unique=False)
    op.create_index('idx_catalog_items_org_catalog_type_status', 'catalog_items', ['organization_id', 'catalog_id', 'resource_type', 'status'], unique=False)
    op.create_index('idx_catalog_items_parent', 'catalog_items', ['parent_item_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_seller_id'), 'catalog_items', ['seller_id'], unique=False)
    op.create_table('tenant_messages',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id', 'conversation_id'], ['tenant_conversations.organization_id', 'tenant_conversations.id'], name='fk_tenant_messages_conversation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['tenant_users.organization_id', 'tenant_users.id'], name='fk_tenant_messages_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'id')
    )
    op.create_index('idx_tenant_messages_org_conversation_created', 'tenant_messages', ['organization_id', 'conversation_id', 'created_at'], unique=False)
    op.create_table('catalog_index_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('catalog_item_id', sa.UUID(), nullable=False),
    sa.Column('item_version', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("operation IN ('upsert', 'delete')", name='ck_catalog_index_events_operation'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'indexed', 'failed', 'dead')", name='ck_catalog_index_events_status'),
    sa.ForeignKeyConstraint(['catalog_item_id', 'catalog_id', 'organization_id'], ['catalog_items.id', 'catalog_items.catalog_id', 'catalog_items.organization_id'], name='fk_catalog_index_events_catalog_item', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_index_events_item_version', 'catalog_index_events', ['catalog_item_id', 'item_version'], unique=False)
    op.create_index('idx_catalog_index_events_pending', 'catalog_index_events', ['organization_id', 'catalog_id', 'status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_catalog_index_events_pending', table_name='catalog_index_events')
    op.drop_index('idx_catalog_index_events_item_version', table_name='catalog_index_events')
    op.drop_table('catalog_index_events')
    op.drop_index('idx_tenant_messages_org_conversation_created', table_name='tenant_messages')
    op.drop_table('tenant_messages')
    op.drop_index(op.f('ix_catalog_items_seller_id'), table_name='catalog_items')
    op.drop_index('idx_catalog_items_parent', table_name='catalog_items')
    op.drop_index('idx_catalog_items_org_catalog_type_status', table_name='catalog_items')
    op.drop_index('idx_catalog_items_index_status', table_name='catalog_items')
    op.drop_index('idx_catalog_items_document', table_name='catalog_items', postgresql_using='gin')
    op.drop_table('catalog_items')
    op.drop_index('idx_usage_org_time', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_tenant_conversations_seller_id'), table_name='tenant_conversations')
    op.drop_index('idx_tenant_conversations_org_user_created', table_name='tenant_conversations')
    op.drop_index('idx_tenant_conversations_org_last_message', table_name='tenant_conversations')
    op.drop_table('tenant_conversations')
    op.drop_index(op.f('ix_tenant_activities_seller_id'), table_name='tenant_activities')
    op.drop_index('idx_tenant_activities_org_user_created', table_name='tenant_activities')
    op.drop_index('idx_tenant_activities_org_type_created', table_name='tenant_activities')
    op.drop_table('tenant_activities')
    op.drop_index('idx_catalogs_org_status', table_name='catalogs')
    op.drop_table('catalogs')
    op.drop_index(op.f('ix_tenant_users_seller_id'), table_name='tenant_users')
    op.drop_index('idx_tenant_users_org_preferences', table_name='tenant_users', postgresql_using='gin')
    op.drop_index('idx_tenant_users_org_email', table_name='tenant_users')
    op.drop_index('idx_tenant_users_org_behavior', table_name='tenant_users', postgresql_using='gin')
    op.drop_table('tenant_users')
    op.drop_table('tenant_configs')
    op.drop_index('idx_synonyms_org', table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index('idx_sellers_org_status', table_name='sellers')
    op.drop_table('sellers')
    op.drop_index('idx_redirects_org_query', table_name='redirect_rules')
    op.drop_table('redirect_rules')
    op.drop_index('idx_pinned_org_query', table_name='pinned_products')
    op.drop_table('pinned_products')
    op.drop_index('idx_merchant_stores_org_status', table_name='merchant_stores')
    op.drop_table('merchant_stores')
    op.drop_index('idx_merchandising_org_query', table_name='merchandising_rules')
    op.drop_table('merchandising_rules')
    op.drop_index('idx_catalog_integrations_org', table_name='catalog_integrations')
    op.drop_table('catalog_integrations')
    op.drop_index('idx_boosts_org', table_name='boost_rules')
    op.drop_table('boost_rules')
    op.drop_index('idx_audit_org_time', table_name='audit_logs')
    op.drop_index('idx_audit_org_resource', table_name='audit_logs')
    op.drop_index('idx_audit_org_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_api_keys_org', table_name='api_keys')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('analytics_daily')
    op.drop_table('organizations')
    # ### end Alembic commands ###
