"""Add search rules

Revision ID: 24a0682e0804
Revises: 9c13d4e6f2a7
Create Date: 2026-07-23 16:05:37.782112

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24a0682e0804'
down_revision: Union[str, Sequence[str], None] = '9c13d4e6f2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirect_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('query_pattern', sa.String(length=255), nullable=False),
    sa.Column('redirect_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_redirect_rules_org', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redirects_org_query', 'redirect_rules', ['organization_id', 'query_pattern'], unique=False)
    
    op.create_table('boost_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('query_pattern', sa.String(length=255), nullable=True),
    sa.Column('attribute_name', sa.String(length=255), nullable=True),
    sa.Column('attribute_value', sa.String(length=255), nullable=True),
    sa.Column('boost_factor', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_boost_rules_org', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_boosts_org', 'boost_rules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_boosts_org', table_name='boost_rules')
    op.drop_table('boost_rules')
    op.drop_index('idx_redirects_org_query', table_name='redirect_rules')
    op.drop_table('redirect_rules')
    # ### end Alembic commands ###
