"""add onboarding flags

Revision ID: c553eb1f6e21
Revises: d1e2f3a4b5c6
Create Date: 2026-07-25 22:58:47.095415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c553eb1f6e21'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchandising_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('query_exact_match', sa.String(length=255), nullable=False),
    sa.Column('pinned_items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('hidden_items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'query_exact_match', name='uix_org_query')
    )
    op.create_index('idx_merchandising_org_query', 'merchandising_rules', ['organization_id', 'query_exact_match'], unique=False)
    # Legacy tables ignored for this migration
    op.add_column('tenant_configs', sa.Column('has_ingested_catalog', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenant_configs', sa.Column('has_merchandising_rules', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_configs', 'has_merchandising_rules')
    op.drop_column('tenant_configs', 'has_ingested_catalog')
    # Legacy tables ignored for this migration
    op.drop_index('idx_merchandising_org_query', table_name='merchandising_rules')
    op.drop_table('merchandising_rules')
    # ### end Alembic commands ###
