"""
Request Models
Pydantic models for API request validation
"""
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


# Base models
class BaseRequest(BaseModel):
    """Base request model"""
    user_id: Optional[str] = Field(None, description="User identifier")

# Chat models
class MessageRole(str, Enum):
    """Chat message roles"""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class ChatCompletionMessage(BaseModel):
    """OpenAI-style chat message"""
    role: MessageRole = Field(..., description="Role of the message sender")
    content: Optional[str] = Field(None, description="Content of the message")
    name: Optional[str] = Field(None, description="Optional name for the message sender")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="Tool calls generated by the model")
    tool_call_id: Optional[str] = Field(None, description="ID of the tool call this message responds to")

class ContextConfig(BaseModel):
    """Configuration for chat context/history"""
    max_history_messages: int = Field(default=20, ge=1, le=100)
    enable_memory: bool = Field(default=True)
    summarize_threshold: int = Field(default=15)

class ChatCompletionRequest(BaseRequest):
    """Production-ready chat completion request"""
    model_version: str = Field(default="gemini-2.5-flash", description="Model version to use")
    messages: List[ChatCompletionMessage] = Field(..., min_length=1, description="List of messages in the conversation")
    conversation_id: Optional[str] = Field(None, description="Conversation identifier")
    stream: bool = Field(default=False, description="Whether to stream the response")
    temperature: float = Field(default=0.7, ge=0, le=2.0)
    max_tokens: Optional[int] = Field(default=2048, ge=1)
    context_config: Optional[ContextConfig] = Field(default_factory=ContextConfig)
    tools: Optional[List[Dict[str, Any]]] = Field(None, description="Available tools for the model")
    image_data: Optional[str] = Field(None, description="Optional base64 encoded image data for vision tasks")

class ChatToolsRequest(BaseRequest):
    """Request for tool discovery or execution"""
    operation: str = Field(..., description="Operation: discover or execute")
    tool_name: Optional[str] = Field(None, description="Tool name (required for execute)")
    parameters: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Parameters for tool execution")

    @field_validator('operation')
    def validate_operation(cls, v):
        allowed = ['discover', 'execute']
        if v not in allowed:
            raise ValueError(f'operation must be one of {allowed}')
        return v

# Search models
class PriceFilter(BaseModel):
    """Price range filter"""
    min: Optional[float] = Field(None, ge=0)
    max: Optional[float] = Field(None, ge=0)

class SearchFilters(BaseModel):
    """Rich search filters"""
    price: Optional[PriceFilter] = None
    category: Optional[List[str]] = None
    brand: Optional[List[str]] = None
    rating: Optional[float] = Field(None, ge=0, le=5)
    sub_category: Optional[List[str]] = None
    stock_only: bool = Field(default=False)
    online_available: Optional[bool] = None

class SortConfig(BaseModel):
    """Sort configuration"""
    by: str = Field(default="relevance")
    order: str = Field(default="desc")

    @field_validator('by')
    def validate_by(cls, v):
        allowed = ['relevance', 'price', 'rating', 'discount', 'newest']
        if v not in allowed:
            raise ValueError(f'sort by must be one of {allowed}')
        return v
    
    @field_validator('order')
    def validate_order(cls, v):
        allowed = ['asc', 'desc']
        if v not in allowed:
            raise ValueError(f'sort order must be one of {allowed}')
        return v

class PaginationConfig(BaseModel):
    """Pagination settings"""
    page: int = Field(default=1, ge=1)
    limit: int = Field(default=20, ge=1, le=100)

class UserContext(BaseModel):
    """User context for personalization"""
    user_id: Optional[str] = None
    session_id: Optional[str] = None
    location: Optional[Dict[str, Any]] = None

class IncludeConfig(BaseModel):
    """Include flags for response content"""
    suggestions: bool = Field(default=False)
    facets: bool = Field(default=False)
    explanations: bool = Field(default=False)

class SearchRequest(BaseRequest):
    """Production-ready product search request"""
    query: str = Field(..., min_length=1, max_length=500, description="Search query")
    filters: Optional[SearchFilters] = Field(default_factory=SearchFilters)
    sort: Optional[SortConfig] = Field(default_factory=SortConfig)
    pagination: Optional[PaginationConfig] = Field(default_factory=PaginationConfig)
    user_context: Optional[UserContext] = Field(default_factory=UserContext)
    search_type: str = Field(default="hybrid", description="Search type: hybrid, keyword, semantic")
    include: Optional[IncludeConfig] = Field(default_factory=IncludeConfig)

    @field_validator('search_type')
    def validate_search_type(cls, v):
        allowed = ['hybrid', 'keyword', 'semantic']
        if v not in allowed:
            raise ValueError(f'search_type must be one of {allowed}')
        return v

class AdvancedSearchRequest(BaseRequest):
    """Advanced search with filters"""
    query: Optional[str] = Field(None, description="Search query")
    category: Optional[str] = Field(None, description="Product category")
    sub_category: Optional[str] = Field(None, description="Product sub-category")
    brand: Optional[str] = Field(None, description="Product brand")
    price_range: Optional[Dict[str, float]] = Field(None, description="Price range filter")
    rating_min: Optional[float] = Field(None, ge=0, le=5, description="Minimum rating")
    discount_min: Optional[float] = Field(None, ge=0, le=100, description="Minimum discount percentage")
    stock_only: bool = Field(default=False, description="Only in-stock products")
    online_available: Optional[bool] = Field(None, description="Online availability filter")
    store_id: Optional[str] = Field(None, description="Store identifier")
    sort_by: str = Field(default="relevance", description="Sort criteria")
    limit: int = Field(default=20, ge=1, le=100, description="Maximum number of results")
    
    @field_validator('sort_by')
    def validate_sort_by(cls, v):
        allowed_sorts = ['relevance', 'price_low', 'price_high', 'rating', 'discount']
        if v not in allowed_sorts:
            raise ValueError(f'sort_by must be one of {allowed_sorts}')
        return v

# Image models
class ImageUploadRequest(BaseRequest):
    """Image upload request with size and format limits"""
    image_data: str = Field(..., description="Base64 encoded image data (max 5MB)")
    message: str = Field(default="I uploaded an image", description="Associated message")
    conversation_id: Optional[str] = Field(None, description="Conversation identifier")
    create_chat_message: bool = Field(default=False, description="Create chat message")
    
    @field_validator('image_data')
    def validate_image_data(cls, v):
        if not v or not v.startswith('data:image/'):
            raise ValueError('Invalid image data format. Must be data:image/...')
        
        # Check format
        allowed_formats = ['image/jpeg', 'image/png', 'image/webp']
        format_found = False
        for fmt in allowed_formats:
            if v.startswith(f'data:{fmt};base64,'):
                format_found = True
                break
        
        if not format_found:
            raise ValueError(f'Invalid format. Allowed: {allowed_formats}')
            
        # Check size (5MB binary is approx 6.7MB base64)
        # base64 length = ceil(n / 3) * 4
        # We can just check the raw string length for a rough estimate
        # 5 * 1024 * 1024 * (4/3) = 6,990,506
        if len(v) > 7000000:
            raise ValueError('Image size exceeds 5MB limit')
            
        return v

class ImageSearchRequest(BaseRequest):
    """Image-based search request"""
    image_id: Optional[str] = Field(None, description="Previously uploaded image ID")
    image_data: Optional[str] = Field(None, description="Base64 encoded image data")
    prompt: str = Field(..., min_length=1, description="Search prompt")
    search_type: str = Field(default="exact_and_similar", description="Search type")
    limit: int = Field(default=10, ge=1, le=50, description="Maximum number of results")
    
    @field_validator('search_type')
    def validate_search_type(cls, v):
        allowed_types = ['exact_match', 'similar_style', 'exact_and_similar']
        if v not in allowed_types:
            raise ValueError(f'search_type must be one of {allowed_types}')
        return v
    
    @field_validator('image_data')
    def validate_image_requirement(cls, v, values):
        if not v and not values.get('image_id'):
            raise ValueError('Either image_data or image_id is required')
        return v

# User models
class UserPreferencesUpdate(BaseModel):
    """User preferences update"""
    preferences: Dict[str, Any] = Field(..., description="User preferences")
    
class UserActivityLog(BaseRequest):
    """User activity logging"""
    activity_type: str = Field(..., description="Activity type")
    product_id: Optional[str] = Field(None, description="Product identifier")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Activity metadata")

# Session models
class SessionStart(BaseRequest):
    """Session start request"""
    location_data: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Location information")

# Conversation models
class ConversationCreate(BaseRequest):
    """Create new conversation"""
    title: Optional[str] = Field(None, description="Conversation title")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Conversation metadata")

class ConversationArchive(BaseRequest):
    """Archive conversation request"""
    conversation_id: str = Field(..., description="Conversation identifier")

# WebSocket models
class WebSocketMessage(BaseModel):
    """WebSocket message structure"""
    event: str = Field(..., description="Event type")
    data: Dict[str, Any] = Field(..., description="Event data")
    user_id: Optional[str] = Field(None, description="User identifier")
    timestamp: Optional[datetime] = Field(default_factory=datetime.now, description="Message timestamp")

class WebSocketAuth(BaseModel):
    """WebSocket authentication"""
    user_id: str = Field(..., description="User identifier")
    user_name: Optional[str] = Field(None, description="User display name")
    language: str = Field(default="en", description="User language preference")

class TypingIndicator(BaseModel):
    """Typing indicator message"""
    user_id: str = Field(..., description="User identifier")
    conversation_id: Optional[str] = Field(None, description="Conversation identifier")
    typing: bool = Field(..., description="Typing status")

# File upload models
class FileUpload(BaseRequest):
    """File upload via WebSocket"""
    file_data: str = Field(..., description="Base64 encoded file data")
    file_name: str = Field(..., description="Original file name")
    file_type: str = Field(..., description="MIME type")
    conversation_id: Optional[str] = Field(None, description="Conversation identifier")
    message: Optional[str] = Field(None, description="Associated message")

# Translation models
class TranslationRequest(BaseModel):
    """Text translation request"""
    text: str = Field(..., min_length=1, description="Text to translate")
    target_language: str = Field(..., description="Target language code")
    source_language: Optional[str] = Field(None, description="Source language code")

# Cache models
class CacheOperation(BaseModel):
    """Cache operation request"""
    key: str = Field(..., description="Cache key")
    value: Optional[Any] = Field(None, description="Cache value")
    ttl: Optional[int] = Field(None, description="Time to live in seconds")